### ISSUE TITLE
Comile error when Gazebo is installed

### ISSUE THREAD

**Issue by Pouya-moh** [corlab/rtt-lwr-hardware-integration#2]
Hi,
We are having a serious issue that has affected all of us. Building this repo, there is a boost shared pointer error which is triggered here first: `rtt-lwr-hardware-integration/src/rtt-lwr-robot.cpp:241` and I _**think**_ is related to some kind of casting, but I can't be sure. 

Fun fact, is that this error wouldn't happen until `gazebo7` and/or `libgazebo7-dev` is installed.

This is rather critical at this point since we have couple of master students that rely on this implementation to finish their thesis, as well as couple of approaching deadlines. So everyone would really appreciate if someone commit to this.
<hr>
To reproduce the error, simply install gazebo and its -dev and then try to build this repository.

**Comment by xwavex** [comment]
Just fixed it I guess ;)

**Comment by Pouya-moh** [comment]
Fixed. Thanks man. Question: I thought it is related to xbotcore but I couldn't figure out and I didn't know there is a "xbotcore new API". Does this mean other repo could get effected? How is the timeline of this new API? I'm asking so that I know about the components that might face the same issue.
Thanks again.

**Comment by xwavex** [comment]
I don't think that it actually affects other components. My guess is that this component just wasn't updated since a long time. And besides, it should only be used in components such as this and other robot components that load the urdf and srdf.
